services:
  # Web Service
  - type: web
    name: flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      celery -A flaskapp.celery_app worker --loglevel=info --concurrency=1 &
      gunicorn "flaskapp:create_app()" --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          name: flask-redis
          type: redis
          property: connectionString
      - key: CHAT_REDIS_URL
        fromService:
          name: flask-redis
          type: redis
          property: connectionString
      # Firebase Web SDK Configuration
      - key: FIREBASE_API_KEY
        value: AIzaSyD3DQtGspj3lNugVxx7y1_9xp6jHSbObho
      - key: FIREBASE_AUTH_DOMAIN
        value: irlmbm.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: irlmbm
      - key: FIREBASE_STORAGE_BUCKET
        value: irlmbm.appspot.com
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: 982307418356
      - key: FIREBASE_APP_ID
        value: 1:982307418356:web:9ccb5775638f5fb40c2ea1
      # Firebase Admin SDK Configuration
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
        value: |
          {
            "type": "service_account",
            "project_id": "irlmbm",
            "private_key_id": "35e9808542b20a471a1c0fca725cece61a63b679",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDKCtHvXlDWgaSR\neVFpuSlC+DCjXwbjmqclXRgBV5oX8nDaE6sp/k7zR8zbtQ7PhGcbXLYBGImN342d\ny46htpwSLIOm4d14Ms6WfKb6JDxKFn7XK8Cx+WippFrWcnJ1WYnyzdKc0flH9ZMP\nDy+31dL7V5xmh2GNQWuR/1eM5hkUJMyCqh6XQfIhheOqSGqiJy50tIaqGhlhiZql\nfN5wjJl6xN/3N2KMqn+5ZkzeMsTrq43Lp2xwKgfjJtEJ8QFHGXsCmAMCAuvWyIve\nEqa/xo1j0+DSgxEVdlMPmRrwVVig+L6veYVbCPn0HYuq3qayUL1TFIYPfxpuJXNQ\npRVeUuunAgMBAAECggEAHjcaCEs5marPurXC+CWpxwso8vW+KQGy54KRmXnJYLVw\nLRzt5xzSH83oFB9ytJQfe1cVHPrXb3E0U5nincqacplXovh6T4SBor3HlvceURIm\nK/WuHq+m+F/M+e8psOUQHVCso6k/N4TBVmo1/68pm08R479xVlenR7FBHaA3tew6\nnKE12eOvMVhBej+RY5vMGzYpULvUEQi+DLL4cDx7LvcbOMcwn8Ntg0j2xPc987Vr\n6od+J7TMAMhXZCtdgI4/4kqJiRZmfATETvpRAv+kVKaF3xeRBIUFKL+zKICsF7TK\nXj6vvVuosN51rzvnUbMNphloQNedhQVV2Pd3rM31WQKBgQD5fslGETCNU7ffygFM\nG6G8OVVmNlThuoVQEyua1ChCRNv5yEmhbNlP2ckg",
            "client_email": "firebase-adminsdk-p4dxq@irlmbm.iam.gserviceaccount.com",
            "client_id": "112233445566778899001",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-p4dxq%40irlmbm.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
      # Google AI Configuration
      - key: GOOGLE_API_KEY
        value: AIzaSyCFDHM6Gti_sKFaPHkEAcYz5pp5T2b4OWs

  # Redis instance
  - type: redis
    name: flask-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
